#ifndef LITE6_PLANNER__KINEMATICS_ENGINE_HPP_
#define LITE6_PLANNER__KINEMATICS_ENGINE_HPP_

#include <array>
#include <vector>
#include <string>
#include <Eigen/Dense>

namespace lite6_planner
{

struct JointLimit {
    double min_pos;
    double max_pos;
    double max_vel;
    double max_acc;
};

struct CartesianLimit {
    double max_trans_vel;
    double max_trans_acc;
    double max_rot_vel;
    double max_rot_acc;
};

// --- Structure to hold evaluated IK solutions for sorting ---
struct IKSolution {
    std::array<double, 6> q;
    double cost_distance; // Weighted joint distance from current pose
    
    // Sort ascending by cost (smaller distance is better)
    bool operator<(const IKSolution& other) const { 
        return cost_distance < other.cost_distance; 
    }
};

class KinematicsEngine
{
public:
    KinematicsEngine();
    
    // Load the physical limits of the robot from YAML
    bool load_limits(const std::string& yaml_path);
    
    // --- Returns a sorted list of all VALID IK solutions ---
    // is_continuous_path = true (e.g., MoveL/MoveC), strictly prohibit quadrant jumps
    bool solve_optimal_ik(const Eigen::Matrix4d& T, 
                          const std::array<double, 6>& q_ref, 
                          std::vector<std::array<double, 6>>& valid_solutions_sorted,
                          bool is_continuous_path);

    // Calculate the singularity measure based on the Jacobian determinant (Maple generated)
    double check_singularity(const std::array<double, 6>& q) const;

    const std::array<JointLimit, 6>& get_joint_limits() const { return joint_limits_; }
    const CartesianLimit& get_cartesian_limits() const { return cart_limits_; }
    double get_singularity_threshold() const { return singularity_threshold_; }

private:
    // Inverse kinematics solver generated by Maple, returns 8 possible configurations
    void raw_inverse_kinematics(const Eigen::Matrix4d& T, double cg0[8][6]) const;

    std::array<JointLimit, 6> joint_limits_;
    CartesianLimit cart_limits_;
    double singularity_threshold_;
    double quadrant_jump_threshold_;
};

} // namespace lite6_planner

#endif // LITE6_PLANNER__KINEMATICS_ENGINE_HPP_